const drivers = [
    {
        id: 1,
        name: 'John Doe',
        age: 35,
        licenseType: 'Class A',
        phone: '123-456-7890',
        address: '123 Main St',
        status: 'Ready',
    },
    {
        id: 2,
        name: 'Jane Smith',
        age: 28,
        licenseType: 'Class B',
        phone: '987-654-3210',
        address: '456 Elm St',
        status: 'Not ready',
    },
    {
        id: 3,
        name: 'Mike Johnson',
        age: 42,
        licenseType: 'Class C',
        phone: '555-123-4567',
        address: '789 Oak St',
        status: 'Ready',
    },
    {
        id: 4,
        name: 'Emily Davis',
        age: 30,
        licenseType: 'Class A',
        phone: '444-555-6666',
        address: '234 Pine St',
        status: 'Ready',
    },
    {
        id: 5,
        name: 'David Wilson',
        age: 45,
        licenseType: 'Class B',
        phone: '777-888-9999',
        address: '567 Maple St',
        status: 'Not ready',
    },
    {
        id: 6,
        name: 'Sarah Brown',
        age: 33,
        licenseType: 'Class C',
        phone: '222-333-4444',
        address: '890 Cedar St',
        status: 'Ready',
    },
    {
        id: 7,
        name: 'Chris Lee',
        age: 40,
        licenseType: 'Class A',
        phone: '666-777-8888',
        address: '345 Walnut St',
        status: 'Ready',
    },
    {
        id: 8,
        name: 'Amanda White',
        age: 31,
        licenseType: 'Class B',
        phone: '999-000-1111',
        address: '678 Birch St',
        status: 'Not ready',
    },
    {
        id: 9,
        name: 'Amanda Black',
        age: 32,
        licenseType: 'Class A',
        phone: '999-020-1111',
        address: '678 Birch St',
        status: 'Not ready',
    },
    {
        id: 10,
        name: 'Amanda Green',
        age: 21,
        licenseType: 'Class C',
        phone: '999-120-1111',
        address: '678 Birch St',
        status: 'Not ready',
    }
];

const vehicles = [
    {
        id: 1,
        licensePlate: '123-456-789',
        type: 'Flatted Truck',
        payload: '1000kg',
        status: 'Working',
        available: 'Yes',
    },
    {
        id: 2,
        licensePlate: '987-654-321',
        type: 'Pickup Truck',
        payload: '600kg',
        status: 'Maintenance',
        available: 'No',
    },
    {
        id: 3,
        licensePlate: '456-789-123',
        type: 'Mini Truck',
        payload: '300kg',
        status: 'Working',
        available: 'Yes',
    },
    {
        id: 4,
        licensePlate: '789-123-456',
        type: 'Pickup Truck',
        payload: '500kg',
        status: 'Working',
        available: 'Yes',
    },
    {
        id: 5,
        licensePlate: '321-654-987',
        type: 'Pickup Truck',
        payload: '850kg',
        status: 'Working',
        available: 'Yes',
    },
    {
        id: 6,
        licensePlate: '654-987-321',
        type: 'Pickup Truck',
        payload: '800kg',
        status: 'Maintenance',
        available: 'No',
    },
    {
        id: 7,
        licensePlate: '987-321-654',
        type: 'Flatted Truck',
        size: 'Large',
        payload: '2000kg',
        status: 'Working',
        available: 'Yes',
    },
    {
        id: 8,
        licensePlate: '789-123-654',
        type: 'Mini Truck',
        size: 'Normal',
        payload: '250kg',
        status: 'Maintenance',
        available: 'No'
    },
    {
        id: 9,
        licensePlate: '456-789-321',
        type: 'Pickup Truck',
        size: 'Large',
        payload: '700kg',
        status: 'Maintenance',
        available: 'No',
    },
    {
        id: 10,
        licensePlate: '123-456-987',
        type: 'Flatted Truck',
        size: 'Large',
        payload: '1600kg',
        status: 'Working',
        available: 'Yes',
    },
];

const trips = [
    {
        route: 'Route A',
        driver: 'Jane Smith',
        vehicle: '123-456-789',
        estimatedCost: '$50',
        departureTime: '9:00 AM',
        expectedArrivalTime: '11:00 AM',
        date: '01/04/2024',
        status: 'Completed',
    },
    {
        route: 'Route B',
        driver: 'John Doe',
        vehicle: '987-654-321',
        estimatedCost: '$80',
        departureTime: '1:30 PM',
        expectedArrivalTime: '5:00 PM',
        date: '01/04/2024',
        status: 'Completed',
    },
    {
        route: 'Route C',
        driver: 'Mike Johnson',
        vehicle: '456-789-123',
        estimatedCost: '$30',
        departureTime: '4:00 PM',
        expectedArrivalTime: '5:00 PM',
        date: '02/04/2024',
        status: 'Completed',
    },
    {
        route: 'Route D',
        driver: 'Emily Davis',
        vehicle: '789-123-456',
        estimatedCost: '$60',
        departureTime: '10:00 AM',
        expectedArrivalTime: '12:30 PM',
        date: '03/04/2024',
        status: 'Completed',
    },
    {
        route: 'Route E',
        driver: 'David Wilson',
        vehicle: '321-654-987',
        estimatedCost: '$40',
        departureTime: '3:00 PM',
        expectedArrivalTime: '4:30 PM',
        date: '03/04/2024',
        status: 'Completed',
    },
    {
        route: 'Route F',
        driver: 'Sarah Brown',
        vehicle: '654-987-321',
        estimatedCost: '$50',
        departureTime: '11:00 AM',
        expectedArrivalTime: '1:00 PM',
        date: '04/04/2024',
        status: 'Completed',
    },
    {
        route: 'Route G',
        driver: 'Chris Lee',
        vehicle: '987-321-654',
        estimatedCost: '$30',
        departureTime: '2:00 PM',
        expectedArrivalTime: '3:00 PM',
        date: '05/04/2024',
        status: 'Completed',
    },
    {
        route: 'Route H',
        driver: 'Amanda White',
        vehicle: '789-123-654',
        estimatedCost: '$60',
        departureTime: '9:30 AM',
        expectedArrivalTime: '12:00 PM',
        date: '06/04/2024',
        status: 'Completed',
    },
    {
        route: 'Route I',
        driver: 'Amanda Black',
        vehicle: '456-789-321',
        estimatedCost: '$30',
        departureTime: '2:30 PM',
        expectedArrivalTime: '3:30 PM',
        date: '07/04/2024',
        status: 'Completed',
    },
    {
        route: 'Route J',
        driver: 'Amanda Green',
        vehicle: '123-456-987',
        estimatedCost: '$50',
        departureTime: '10:30 AM',
        expectedArrivalTime: '12:30 PM',
        date: '07/04/2024',
        status: 'Completed',
    },
    /*
    {
        route: 'Route K',
        estimatedTime: '1.5 hours',
        estimatedCost: '$40',
        departureTime: '3:30 PM',
        expectedArrivalTime: '5:00 PM',
        status: 'Pending',
    },
    {
        id: 12,
        route: 'Route L',
        estimatedTime: '3 hours',
        estimatedCost: '$70',
        departureTime: '9:00 AM',
        expectedArrivalTime: '12:00 PM',
        status: 'In progress',
    },
    {
        id: 13,
        route: 'Route M',
        estimatedTime: '2.5 hours',
        estimatedCost: '$60',
        departureTime: '1:00 PM',
        expectedArrivalTime: '3:30 PM',
        status: 'Scheduled',
    },
    {
        id: 14,
        route: 'Route N',
        estimatedTime: '1 hour',
        estimatedCost: '$30',
        departureTime: '4:30 PM',
        expectedArrivalTime: '5:30 PM',
        status: 'In progress',
    },
    {
        id: 15,
        route: 'Route O',
        estimatedTime: '2 hours',
        estimatedCost: '$50',
        departureTime: '11:30 AM',
        expectedArrivalTime: '1:30 PM',
        status: 'Scheduled',
    },
    {
        id: 16,
        route: 'Route P',
        estimatedTime: '1.5 hours',
        estimatedCost: '$40',
        departureTime: '2:30 PM',
        expectedArrivalTime: '4:00 PM',
        status: 'Pending',
    },
    {
        id: 17,
        route: 'Route Q',
        estimatedTime: '3 hours',
        estimatedCost: '$70',
        departureTime: '9:30 AM',
        expectedArrivalTime: '12:30 PM',
        status: 'In progress',
    },
    {
        id: 18,
        route: 'Route R',
        estimatedTime: '2.5 hours',
        estimatedCost: '$60',
        departureTime: '1:30 PM',
        expectedArrivalTime: '4:00 PM',
        status: 'Scheduled',
    },
    {
        id: 19,
        route: 'Route S',
        estimatedTime: '1 hour',
        estimatedCost: '$30',
        departureTime: '3:00 PM',
        expectedArrivalTime: '4:00 PM',
        status: 'Completed',
    },
    {
        id: 20,
        route: 'Route T',
        estimatedTime: '2.5 hours',
        estimatedCost: '$60',
        departureTime: '10:00 AM',
        expectedArrivalTime: '12:30 PM',
        status: 'Scheduled',
    },*/
];